const cards = [
  {
    id: 1,
    image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
    nameRU: "name",
    trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
    duration: 100,
  },
  {
    id: 2,
    image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
    nameRU: "name",
    trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
    duration: 10,
  },
  // {
  //   id: 3,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 140,
  // },
  // {
  //   id: 4,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 50,
  // },
  // {
  //   id: 5,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 160,
  // },
  // {
  //   id: 6,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 170,
  // },
  // {
  //   id: 7,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 180,
  // },
  // {
  //   id: 8,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 190,
  // },
  // {
  //   id: 9,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 200,
  // },
  // {
  //   id: 10,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 180,
  // },
  // {
  //   id: 11,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 190,
  // },
  // {
  //   id: 12,
  //   image: "https://www.kartinki24.ru/uploads/gallery/main/30/kartinki24_ru_flower_fun_107.jpg",
  //   nameRU: "name",
  //   trailerLink: "https://www.youtube.com/watch?v=iWeK-vWAmlo",
  //   duration: 200,
  // },
];

export default cards;