export const films = [
  {
    country: 'Antarctica',
    director: 'Evil dictator',
    duration: 333,
    year: '2216',
    description: 'The evil dictator is destroying the earth',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Кровавый диктатор',
    nameEN: 'Evil dictator',
    _id: '1',
  },
  {
    country: 'Russia',
    director: 'Presic',
    duration: 111,
    year: '2256',
    description: 'Презиком становится джорщ бущ средний',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Вася Пупович',
    nameEN: 'Vasya Pupovich',
    _id: '2',
  },
  {
    country: 'USA',
    director: 'Put IN',
    duration: 23552,
    year: '2016',
    description: 'Вася захватывает землю всю',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Кровавый диктатор',
    nameEN: 'Evil dictator',
    _id: '3',
  },
  {
    country: 'Африка',
    director: 'Капоне Эдь',
    duration: 13242342,
    year: '2358',
    description: 'ааааааааааа аааааааааа аа а  аа ааааааааааа ааа а а ааааааааааааа',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Ааааа аа аа',
    nameEN: 'аа а а а  а а',
    _id: '4',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '5',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '6',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '7',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '8',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '9',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '10',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '11',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '12',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '13',
  },
  {
    country: 'Russia Mafia',
    director: 'Иван Павлович Прижевалов',
    duration: 13124142,
    year: '2020',
    description: 'Желтый Джо уходит в закат под музыку',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Желтый Джо',
    nameEN: 'Yellow Joh',
    _id: '14',
  },
  {
    country: 'Antarctica state',
    director: 'Evil dictator',
    duration: 666,
    year: '2256',
    description: 'The evil dictator is destroying the earth',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Кровавый диктатор',
    nameEN: 'Evil dictator',
    _id: '15',
  },
  {
    country: 'Antarctica state',
    director: 'Evil dictator',
    duration: 666,
    year: '2256',
    description: 'The evil dictator is destroying the earth',
    image: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    trailerLink: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    thumbnail: 'https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg',
    nameRU: 'Кровавый диктатор',
    nameEN: 'Evil dictator',
    _id: '16',
  },
];

export const savedFilms = [
  {
    country: 'Small country',
    director: 'Egor',
    duration: 103,
    year: '1987',
    description: 'Egor conquers the world stage',
    image:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    trailerLink:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    thumbnail:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    nameRU: 'Веселый Егор',
    nameEN: 'Cheerful Egor',
    _id: '17',
  },
  {
    country: 'Small country',
    director: 'Egor',
    duration: 103,
    year: '1987',
    description: 'Egor conquers the world stage',
    image:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    trailerLink:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    thumbnail:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    nameRU: 'Веселый Егор',
    nameEN: 'Cheerful Egor',
    _id: '18',
  },
  {
    country: 'Small country',
    director: 'Egor',
    duration: 103,
    year: '1987',
    description: 'Egor conquers the world stage',
    image:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    trailerLink:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    thumbnail:
      'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse',
    nameRU: 'Веселый Егор',
    nameEN: 'Cheerful Egor',
    _id: '19',
  },
];
